name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Permission Gradlew
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build

  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Run all tests
        run: ./gradlew test -i
